apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-correlations
  namespace: monitoring
data:
  pod-logs.yaml: |
    apiVersion: 1
    correlations:
      - orgId: 1
        name: "View pod logs"
        description: "Prometheus → Loki"
        source:
          datasourceUid: "PROM"
          fields:
            - name: "namespace"
              selectors: ["namespace"]
            - name: "pod"
              selectors: ["pod"]
            # - name: "container"
            #   selectors: ["container"]
        target:
          datasourceUid: "LOKI"
          queries:
            - query: '{namespace="${namespace}", pod="${pod}"}'

