# petclinic-db-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: petclinic-db-secret
  namespace: petclinic-ns
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "admin"
  SPRING_DATASOURCE_PASSWORD: "poweradmin!"

